#ifndef ATARIX_RESOURCE_TYPES_H
#define ATARIX_RESOURCE_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#define ATARIX_RESOURCE_INVALID 0x0000u

#define ATARIX_RESOURCE_MAILBOX 0x0001u
#define ATARIX_RESOURCE_DMA 0x0002u
#define ATARIX_RESOURCE_TIMER 0x0003u
#define ATARIX_RESOURCE_INTERRUPT_CONTROLLER 0x0004u
#define ATARIX_RESOURCE_GPIO 0x0005u
#define ATARIX_RESOURCE_UART 0x0006u
#define ATARIX_RESOURCE_FABRIC_MEMORY 0x0007u
#define ATARIX_RESOURCE_SHARED_MEMORY 0x0008u
#define ATARIX_RESOURCE_EVENT_QUEUE 0x0009u

#define ATARIX_RESOURCE_ENUMERATION_FABRIC 0x000Au
#define ATARIX_RESOURCE_MANAGEMENT_FABRIC 0x000Bu
#define ATARIX_RESOURCE_TRANSPORT_FABRIC 0x000Cu

#define ATARIX_RESOURCE_SUPERVISOR 0x0010u
#define ATARIX_RESOURCE_HEALTH_MONITOR 0x0011u
#define ATARIX_RESOURCE_PROVISIONING_ENGINE 0x0012u
#define ATARIX_RESOURCE_VALIDATION_ENGINE 0x0013u

#define ATARIX_RESOURCE_LOGIC_ANALYZER 0x1000u
#define ATARIX_RESOURCE_OSCILLOSCOPE 0x1001u
#define ATARIX_RESOURCE_DSP 0x1002u
#define ATARIX_RESOURCE_PATTERN_GENERATOR 0x1003u
#define ATARIX_RESOURCE_PROTOCOL_DECODER 0x1004u
#define ATARIX_RESOURCE_COUNTER_BANK 0x1005u
#define ATARIX_RESOURCE_TRIGGER_ROUTER 0x1006u
#define ATARIX_RESOURCE_TRACE_BUFFER 0x1007u

#define ATARIX_RESOURCE_CPU 0x2000u
#define ATARIX_RESOURCE_CPU_DIAGNOSTICS 0x2001u
#define ATARIX_RESOURCE_CPU_TRACE 0x2002u
#define ATARIX_RESOURCE_CPU_HEALTH 0x2003u
#define ATARIX_RESOURCE_CPU_BOOT_STATUS 0x2004u

#define ATARIX_RESOURCE_NETWORK_INTERFACE 0x3000u
#define ATARIX_RESOURCE_PACKET_ENGINE 0x3001u
#define ATARIX_RESOURCE_NETWORK_BOOT 0x3002u

#define ATARIX_RESOURCE_BLOCK_STORAGE 0x4000u
#define ATARIX_RESOURCE_FILE_STORAGE 0x4001u
#define ATARIX_RESOURCE_ROM_STORAGE 0x4002u
#define ATARIX_RESOURCE_CONFIGURATION_STORAGE 0x4003u

#define ATARIX_RESOURCE_GPU 0x6000u
#define ATARIX_RESOURCE_AI_ACCELERATOR 0x6001u
#define ATARIX_RESOURCE_VECTOR_ENGINE 0x6002u
#define ATARIX_RESOURCE_FPGA_COMPUTE 0x6003u
#define ATARIX_RESOURCE_CRYPTO_ENGINE 0x6004u

#define ATARIX_RESOURCE_EXPERIMENTAL_BEGIN 0x8000u
#define ATARIX_RESOURCE_EXPERIMENTAL_END 0xFFFFu

static inline int atarix_resource_is_experimental(unsigned int resource_type) {
    return resource_type >= ATARIX_RESOURCE_EXPERIMENTAL_BEGIN &&
           resource_type <= ATARIX_RESOURCE_EXPERIMENTAL_END;
}

#ifdef __cplusplus
}
#endif

#endif /* ATARIX_RESOURCE_TYPES_H */
