#ifndef ATARIX_SERVICE_IDS_H
#define ATARIX_SERVICE_IDS_H

#ifdef __cplusplus
extern "C" {
#endif

#define ATARIX_SERVICE_INVALID 0x0000u

#define ATARIX_SERVICE_DISCOVERY 0x0001u
#define ATARIX_SERVICE_DIRECTORY 0x0002u
#define ATARIX_SERVICE_PROVISIONING 0x0003u
#define ATARIX_SERVICE_VALIDATION 0x0004u
#define ATARIX_SERVICE_MONITOR 0x0005u
#define ATARIX_SERVICE_HEALTH 0x0006u
#define ATARIX_SERVICE_FAULT_LOG 0x0007u
#define ATARIX_SERVICE_EVENT_LOG 0x0008u
#define ATARIX_SERVICE_TIMEBASE 0x0009u
#define ATARIX_SERVICE_MAILBOX 0x000Au
#define ATARIX_SERVICE_DMA 0x000Bu
#define ATARIX_SERVICE_INTERRUPT_ROUTING 0x000Cu
#define ATARIX_SERVICE_RECOVERY 0x000Du

#define ATARIX_SERVICE_INSTRUMENTATION 0x1000u
#define ATARIX_SERVICE_CAPTURE 0x1001u
#define ATARIX_SERVICE_ANALYSIS 0x1002u
#define ATARIX_SERVICE_TRACE 0x1003u
#define ATARIX_SERVICE_LOGIC_ANALYZER 0x1004u
#define ATARIX_SERVICE_OSCILLOSCOPE 0x1005u
#define ATARIX_SERVICE_PATTERN_GENERATOR 0x1006u
#define ATARIX_SERVICE_PROTOCOL_DECODER 0x1007u
#define ATARIX_SERVICE_COUNTERS 0x1008u
#define ATARIX_SERVICE_TRIGGER_ROUTER 0x1009u

#define ATARIX_SERVICE_CPU_DIAGNOSTICS 0x2000u
#define ATARIX_SERVICE_CPU_HEALTH 0x2001u
#define ATARIX_SERVICE_CPU_TRACE 0x2002u
#define ATARIX_SERVICE_CPU_BOOT_STATUS 0x2003u
#define ATARIX_SERVICE_CPU_VALIDATION 0x2004u

#define ATARIX_SERVICE_NETWORK_INTERFACE 0x3000u
#define ATARIX_SERVICE_NETWORK_BOOT 0x3001u
#define ATARIX_SERVICE_PACKET_TRANSPORT 0x3002u
#define ATARIX_SERVICE_TIME_SYNC 0x3003u

#define ATARIX_SERVICE_BLOCK_STORAGE 0x4000u
#define ATARIX_SERVICE_FILE_STORAGE 0x4001u
#define ATARIX_SERVICE_ROM_STORAGE 0x4002u
#define ATARIX_SERVICE_CONFIGURATION_STORAGE 0x4003u

#define ATARIX_SERVICE_GPU_COMPUTE 0x6000u
#define ATARIX_SERVICE_AI_ACCELERATION 0x6001u
#define ATARIX_SERVICE_VECTOR_COMPUTE 0x6002u
#define ATARIX_SERVICE_FPGA_COMPUTE 0x6003u
#define ATARIX_SERVICE_CRYPTO_ACCELERATION 0x6004u

#define ATARIX_SERVICE_EXPERIMENTAL_BEGIN 0x8000u
#define ATARIX_SERVICE_EXPERIMENTAL_END 0xFFFFu

static inline int atarix_service_is_experimental(unsigned int service_id) {
    return service_id >= ATARIX_SERVICE_EXPERIMENTAL_BEGIN &&
           service_id <= ATARIX_SERVICE_EXPERIMENTAL_END;
}

#ifdef __cplusplus
}
#endif

#endif /* ATARIX_SERVICE_IDS_H */
