#!/usr/bin/env python3
from pathlib import Path
import argparse
import sys

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
OUT = ROOT / "build" / "ATARIX-DOCS-BOOK.md"
NAMES = {"architecture": "Architecture", "design": "Design", "engineering": "Engineering", "reviews": "Reviews"}


def strip_meta(text: str) -> str:
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            return text[end + 4:].strip()
    return text.strip()


def area(path: Path, root: Path) -> str:
    rel = path.relative_to(root)
    key = rel.parts[0] if rel.parts else "other"
    return NAMES.get(key, key.replace("-", " ").replace("_", " ").title())


def build(docs: Path, out: Path) -> int:
    files = sorted(p for p in docs.rglob("*.md") if p.is_file())
    if not files:
        print(f"FAIL no Markdown files found under: {docs}")
        return 1
    groups = {}
    for p in files:
        groups.setdefault(area(p, docs), []).append(p)
    book = ["# ATARIX COMPLETE DOCUMENTATION BOOK", "", "Generated by AEMS from the docs tree.", "", "## Table of Contents", ""]
    for name in sorted(groups):
        book.append(f"- {name}")
        for p in sorted(groups[name]):
            book.append(f"  - `{p.relative_to(ROOT)}`")
    book += ["", "---", ""]
    idx = 0
    for name in sorted(groups):
        book += [f"# {name}", ""]
        for p in sorted(groups[name]):
            idx += 1
            rel = p.relative_to(ROOT)
            print(f"PASS include {idx:03d}: {rel}")
            book += [f"## File {idx:03d}: `{rel}`", "", strip_meta(p.read_text(encoding="utf-8")), "", "---", ""]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(book).rstrip() + "\n", encoding="utf-8")
    print(f"PASS wrote docs book: {out.relative_to(ROOT)}")
    print(f"AEMS DOCS BOOK RESULT: PASS files={len(files)} groups={len(groups)}")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--docs-dir", type=Path, default=DOCS)
    parser.add_argument("--output", type=Path, default=OUT)
    args = parser.parse_args(argv)
    return build(args.docs_dir, args.output)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
