#!/usr/bin/env python3
from pathlib import Path
import argparse
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
OUT = ROOT / "build" / "ATARIX-DOCS-BOOK.md"

CHAPTERS = [
    (1, "Purpose and Scope", ["purpose", "scope", "design-001", "design-002"]),
    (2, "Historical Context", ["historical", "history", "context"]),
    (3, "Documentation Taxonomy", ["taxonomy", "style-guide", "documentation"]),
    (4, "Architecture Before Implementation", ["architecture-before", "review", "architecture-review"]),
    (5, "Security Before Convenience", ["security", "authority", "policy"]),
    (6, "Human Readability", ["readability", "human"]),
    (7, "Fabric-Centric Computing", ["fabric-centric", "fabric"]),
    (8, "Engineering as Architecture", ["engineering-as", "engineering"]),
    (9, "System Layers", ["system-layers", "layers", "spec-001", "spec-002", "spec-003", "spec-005"]),
    (10, "Object Model", ["object", "object-model"]),
    (11, "Capability Model", ["capability", "capabilities"]),
    (12, "Mailbox Transport", ["mailbox", "transport"]),
    (13, "Directory and Discovery Services", ["directory", "discovery"]),
    (14, "Memory and Data Movement", ["memory", "data-movement", "spec-021"]),
    (15, "Lookup Acceleration", ["lookup", "acceleration", "hash", "index", "spec-020"]),
    (16, "Processor Modules", ["processor", "module"]),
    (17, "Fabric Northbridge", ["northbridge"]),
    (18, "Supervisor Controller", ["supervisor", "controller"]),
    (19, "Storage and Networking", ["storage", "network"]),
    (20, "AEMS and Engineering Gates", ["aems", "gate", "gates", "spec-090", "spec-091"]),
    (21, "Requirements and Traceability", ["requirements", "traceability", "trace"]),
    (22, "Roadmap and Evolution", ["roadmap", "evolution"]),
]
APPENDIX = "Appendix: Supporting Documents"


def strip_meta(text: str) -> str:
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            return text[end + 4:].strip()
    return text.strip()


def chapter_title(number: int, title: str) -> str:
    return f"Chapter {number}: {title}"


def score(path: Path, body: str, needles: list[str]) -> int:
    hay = f"{path.as_posix()}\n{body[:4000]}".lower()
    total = 0
    for needle in needles:
        if needle.lower() in hay:
            total += 1
    return total


def bucket(path: Path, body: str) -> str:
    rel = path.relative_to(DOCS).as_posix().lower()
    m = re.search(r"atx-100/chapters/(\d+)-", rel)
    if m:
        n = int(m.group(1))
        for number, title, _ in CHAPTERS:
            if number == n:
                return chapter_title(number, title)
    best = (0, APPENDIX)
    for number, title, needles in CHAPTERS:
        value = score(path, body, needles)
        if value > best[0]:
            best = (value, chapter_title(number, title))
    return best[1]


def build(docs: Path, out: Path) -> int:
    files = sorted(p for p in docs.rglob("*.md") if p.is_file())
    if not files:
        print(f"FAIL no Markdown files found under: {docs}")
        return 1
    items = []
    groups = {}
    for p in files:
        body = strip_meta(p.read_text(encoding="utf-8"))
        name = bucket(p, body)
        groups.setdefault(name, []).append((p, body))
        items.append(p)
    order = [chapter_title(n, t) for n, t, _ in CHAPTERS] + [APPENDIX]
    book = ["# ATARIX COMPLETE DOCUMENTATION BOOK", "", "Generated by AEMS from docs/**/*.md and bucketed into ATX-100 chapters.", "", "## Table of Contents", ""]
    for name in order:
        if name not in groups:
            continue
        book.append(f"- {name}")
        for p, _ in sorted(groups[name]):
            book.append(f"  - `{p.relative_to(ROOT)}`")
    book += ["", "---", ""]
    idx = 0
    for name in order:
        if name not in groups:
            continue
        book += [f"# {name}", ""]
        for p, body in sorted(groups[name]):
            idx += 1
            rel = p.relative_to(ROOT)
            print(f"PASS include {idx:03d}: {rel} -> {name}")
            book += [f"## File {idx:03d}: `{rel}`", "", body, "", "---", ""]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(book).rstrip() + "\n", encoding="utf-8")
    print(f"PASS wrote docs book: {out.relative_to(ROOT)}")
    print(f"AEMS DOCS BOOK RESULT: PASS files={len(items)} buckets={len(groups)}")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--docs-dir", type=Path, default=DOCS)
    parser.add_argument("--output", type=Path, default=OUT)
    args = parser.parse_args(argv)
    return build(args.docs_dir, args.output)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
