#!/usr/bin/env python3
"""Build one Markdown book from every docs Markdown file.

This is intentionally simple: walk docs/ recursively, strip YAML front matter,
sort paths, and concatenate the documents into build/ATARIX-DOCS-BOOK.md.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DOCS_DIR = ROOT / "docs"
DEFAULT_OUTPUT = ROOT / "build" / "ATARIX-DOCS-BOOK.md"
DEFAULT_EXCLUDES = {
    "build",
    ".git",
    ".github",
    "node_modules",
    "__pycache__",
}


def strip_front_matter(text: str) -> str:
    if not text.startswith("---\n"):
        return text.strip()
    end = text.find("\n---", 4)
    if end == -1:
        return text.strip()
    return text[end + len("\n---") :].strip()


def should_skip(path: Path) -> bool:
    return any(part in DEFAULT_EXCLUDES for part in path.parts)


def iter_markdown_files(root: Path) -> list[Path]:
    return sorted(
        path for path in root.rglob("*.md")
        if path.is_file() and not should_skip(path.relative_to(ROOT))
    )


def build_docs_book(docs_dir: Path, output_path: Path) -> int:
    if not docs_dir.is_dir():
        print(f"FAIL docs directory missing: {docs_dir}")
        return 1

    files = iter_markdown_files(docs_dir)
    if not files:
        print(f"FAIL no Markdown files found under: {docs_dir}")
        return 1

    book: list[str] = []
    book.append("# ATARIX COMPLETE DOCUMENTATION BOOK")
    book.append("")
    book.append("Generated by AEMS from docs/**/*.md.")
    book.append("")
    book.append("## Table of Contents")
    book.append("")

    for path in files:
        rel = path.relative_to(ROOT)
        book.append(f"- `{rel}`")

    book.append("")
    book.append("---")
    book.append("")

    for index, path in enumerate(files, 1):
        rel = path.relative_to(ROOT)
        print(f"PASS include {index:03d}: {rel}")
        body = strip_front_matter(path.read_text(encoding="utf-8"))
        book.append(f"# File {index:03d}: `{rel}`")
        book.append("")
        book.append(body)
        book.append("")
        book.append("---")
        book.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(book).rstrip() + "\n", encoding="utf-8")
    print(f"PASS wrote docs book: {output_path.relative_to(ROOT)}")
    print(f"AEMS DOCS BOOK RESULT: PASS files={len(files)}")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Build one Markdown book from docs/**/*.md")
    parser.add_argument("--docs-dir", type=Path, default=DEFAULT_DOCS_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    return build_docs_book(args.docs_dir, args.output)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
